// Generated by pipeline/build_web.py - do not edit.
const CACHE = "ksiazulo-f776ef3b7f9e";
const ASSETS = ["./", "index.html", "match.js", "ui.js", "list-common.js", "list.js", "list.css", "ui.css", "lib/leaflet.min.js", "lib/leaflet.min.css", "data/places.json", "data/basemap.geojson", "manifest.webmanifest", "icon-192.png", "icon-512.png"];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache first: the whole app is static and works offline once installed.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true })
    .then((hit) => hit || fetch(e.request)));
});
